version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: trishpay_airmail
      MYSQL_USER: airmailuser
      MYSQL_PASSWORD: StrongPassword123
      MYSQL_ROOT_PASSWORD: RootPassword123
    ports:
      # ⚠️ Local debugging ke liye open. Production me isko comment-out rakho.
      # - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pr8ajx9HzHOd8"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  backend:
    build: .
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      # Ensure backend DB host is the docker service name 'mysql'
      DATABASE_URL: mysql://trishpay_airmail:r8ajx9HzHOd8@mysql:3306/trishpay_airmail
      # ↑ ye .env ki value ko override karega. Agar .env me remote/CWP wali value hai to hata do.
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - "3000"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
